### ISSUE TITLE
Forcing Minimum App Version in Internal Testing / TestFlight Stage

### ISSUE THREAD

**Issue by serpentarius-hollow** [larryaasen/upgrader#177]
Hi! I was wondering can we try to force the minimum app version while our app is still in Internal Testing/TestFlight stage? Thank you.

**Comment by larryaasen** [comment]
@serpentarius-hollow While you are still doing internal testing I assume your app is not published on a store yet, so the minimum app version does not do anything, like you pointed out. You can force the alert to be displayed by setting `debugDisplayAlways`. Otherwise, you can look into using an [Appcast](https://pub.dev/packages/upgrader#appcast).
