### ISSUE TITLE
Android did not prompt for upgrade. Do you need to configure appcast

### ISSUE THREAD

**Issue by 549064368** [larryaasen/upgrader#223]
Android did not prompt for upgrade. Do you need to configure appcast

**Comment by larryaasen** [comment]
@549064368 Can you provide the Flutter console log so we can review this issue for you? [Reporting Issues](https://github.com/larryaasen/upgrader#reporting-issues)

**Comment by romarito** [comment]
This also happened with my apps, I published updates this week and the versions that were in use used the 4.2 upgrader and none of them showed the warning prompt at any time of the day.
The Google Play app ended up doing a silent update at night, I don't know what kind of additional information I could send you now since it runs flutter doctor it will be with upgrader 4.10, but the failure, in my case, occurred in 4.2.

**Comment by larryaasen** [comment]
Look at the release notes for version 4.2.1 https://pub.dev/packages/upgrader/changelog#421

**Comment by larryaasen** [comment]
@549064368 Can this issue be closed?
