### ISSUE TITLE
Setup with GoRouter

### ISSUE THREAD

**Issue by deepak-kumar-swain** [larryaasen/upgrader#259]
With GoRouter, where to initiate Upgrader

**Comment by krishnatejakanchi** [comment]
Yes, currently we are facing issues.

**Comment by larryaasen** [comment]
Can you wrap your existing widget from the MaterialApp.home like this?
```
    return MaterialApp(
      title: 'Upgrader Example',
      home: UpgradeAlert(
          child: Scaffold(
        appBar: AppBar(title: Text('Upgrader Example')),
        body: Center(child: Text('Checking...')),
      )),
    );
```

**Comment by kyeshmz** [comment]
yeah same thing here, I am using MaterialApp.router, which doesn't disclose a child

**Comment by LenhartStephan** [comment]
Here is a related issue on that topic: https://github.com/flutter/flutter/issues/103009
The main takeaway: It's not feasible to insert a widget below the navigator if you use `MaterialApp.router` without creating a big mess.

But there is a workaround by exposing the key from the router config (routerConfig.routerDelegate.navigatorKey) and using it's context to display the dialog within upgrade_alert.dart. This would require some changes to this package.
(See 'working example' at the bottom of https://github.com/flutter/flutter/issues/103009#issue-1224839612)

**Comment by larryaasen** [comment]
I have a fix for this now. Here is the planned documentation which you can now see on the master branch. Please check this out and see it if will work for you. 

_When using GoRouter (pacakge go_router) with upgrader, you may need to provide a navigatorKey to the UpgradeAlert widget so that the correct route context is used. Below is part of the code you will need for this. Also, checkout the [example/lib/main-gorouter.dart](https://file+.vscode-resource.vscode-cdn.net/Users/larry/Projects/upgrader/example/lib/main-gorouter.dart) example for a more complete example._
```
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Upgrader GoRouter Example',
      routerConfig: routerConfig,
      builder: (context, child) {
        return UpgradeAlert(
          navigatorKey: routerConfig.routerDelegate.navigatorKey,
          child: child ?? Text('child'),
        );
      },
    );
  }
```

**Comment by kyeshmz** [comment]
Seems good, would be great to know when it releases!

**Comment by larryaasen** [comment]
I just published a pre-release version that you can try here: [7.1.0-alpha.2](https://pub.dev/packages/upgrader/versions/7.1.0-alpha.2)

Please provide feedback here on how this solves your problem with GoRouter.

**Comment by chrisbin-kutuki** [comment]
@larryaasen Yes. This works.. Thank you for this🎉🎉
