### ISSUE TITLE
Country Code initialisation?

### ISSUE THREAD

**Issue by NTMS2017** [larryaasen/upgrader#85]
How can I initialise Country Code?

I did as   **Upgrader().countryCode = "tr";** and my question if this is the correct version of country code usage?

In page initialisation (void initState() )I check if Platform.isIOS. If iOS use Future _checkForIOSUpdate() async to check if new version available. And I build my messages using _buildIOSUpdate().

Again is this way of coding is correct?

**My full code for iOS:**

  ```
  /// (5) CHECK FOR IOS UPDATE
  Future _checkForIOSUpdate() async {
    setState(() {
      _runUpdateLoading = true;
    });

    Upgrader().clearSavedSettings();
    Upgrader().countryCode = "tr";
    Upgrader().debugDisplayAlways = false;
    Upgrader().debugDisplayOnce = false;
    await Upgrader().initialize();
    bool _isAvailable = Upgrader().isUpdateAvailable();

    await Future.delayed(Duration(milliseconds: 250));

    //print('_isAvailable: $_isAvailable');

    if (_isAvailable == true) {
      setState(() {
        _checkUpdate = true;
        _runUpdateLoading = false;
      });
    } else {
      setState(() {
        _checkUpdate = false;
        _runUpdateLoading = false;
      });
    }
  }();


/// IOS UPDATE
  Widget _buildIOSUpdate(BuildContext context) {
    //Upgrader().clearSavedSettings();

    return WillPopScope(
      onWillPop: _requestAppExitPop,
      child: new Scaffold(
          appBar: new AppBar(
            elevation: 0.0,
            backgroundColor: capitalDarkYellow,
            title: new Text(
              "Güncelleme Uyarısı",
              style: new TextStyle(fontSize: 14.0, color: Colors.white),
            ),
          ),
          key: _scaffoldKeyLogin,
          resizeToAvoidBottomPadding: false,
          backgroundColor: capitalLightYellow,
          body: UpgradeAlert(
            debugLogging: true,
            showIgnore: false,
            showLater: false,
            child: Center(
                child: Text(
                    "- Uygulamanın yeni sürümü mevcut.\n\n- Uygulamayı güncellemeniz gerekmektedir.\n\n-Eski sürümler kararlı çalışmayabilir.\n\nHer zaman iOS sürümünüzü ve Uygulama sürümünüzü güncel tutmanızı öneriyoruz.")),
          )),
    );
  }
```

**Comment by MojtabaTavakkoli** [comment]
As comes from your main question, if you want to change alert dialog language you have to do it like so:

`UpgradeAlert(messages: UpgraderMessages(code: 'es'));`

the above was a simple sample code in the documents here: https://github.com/larryaasen/upgrader#language-localization

and specific for your case it should be look like this:

**Comment by NTMS2017** [comment]
Thanks for info. And sorry for my English. I am trying to understand how to connect Turkish App Store? It wasn’t my intention to ask the diolag alert language. 

Is it possible to use below code to access Turkish App Store?

My app in Turkish App Store and Plugin default is US.


`Upgrader().countryCode = "tr";`

**Comment by MojtabaTavakkoli** [comment]
Aha now I see. It's all fine.
I had the same exact issue and its already answered here: [https://github.com/larryaasen/upgrader/issues/83](url)
Take a look.

**Comment by MojtabaTavakkoli** [comment]
Aha now I see. It's all fine.
I had the same exact issue and its already answered here: https://github.com/larryaasen/upgrader/issues/83
Take a look.

**Comment by NTMS2017** [comment]
Thanks for the info. But #83 is abot 
“ another market except App Store or Google Play”!!!

My question was Turkish App Store.

**Comment by MojtabaTavakkoli** [comment]
Yes I totally understand. Use that approach and it will solve your problem. 
The AppCast is your answer.

**Comment by NTMS2017** [comment]
Thanks. 

Without using appcast (for ios) can I use below code and check or access the app version in Turkish App Store?

`Upgrader().countryCode = "tr";`

**Comment by MojtabaTavakkoli** [comment]
Well you better wait for the owner of the package to answer this. They usually respond in 2 days.

**Comment by NTMS2017** [comment]
Thanks 👍🙏
I will wait.

**Comment by larryaasen** [comment]
This is from the [README](https://github.com/larryaasen/upgrader#ios-country-code) and I think it will solve your problem.

## iOS Country Code
When your app is not in the iOS `US` App Store, which is the default, you must use the `countryCode` parameter mentioned above. The upgrader package does not know which country app store to use because it is not provided by Apple. It assumes
the app is in the `US` App Store.

So, your code `Upgrader().countryCode = "tr";` should work as long as it is called before `Upgrader().initialize();`.

Also, you should not call `clearSavedSettings()` except when debugging because it removes the internally saved values. Don't use that in your release code.

If you have any more problems, please include your package version, Flutter version, and debug log in a comment.

**Comment by fabricio-godoi** [comment]
@NTMS2017 If you are yet wondering about this configuration since the Upgrader sens to use a singleton in its library it is possible to set up de countryCode as you suggested. But in the UpgradeAlert widget has a countryCode configuration as well that you can provide (as the library specifies). Just check if the initialize is not called before you use the UpgradeAlert.

Also, be aware that I found some bugs regarding the case sensitiveness, always use UPPERCASE for better results.
Upgrader().countryCode = "TR";

See this issue https://github.com/larryaasen/upgrader/issues/100 that I just open explaining my findings.

**Comment by larryaasen** [comment]
Closed due to lack of activity. You can open a new issue if you have more questions.
